services:
  mysql:
    image: 'mysql:8.0'
    container_name: "mysql_batch"
    build: .
    ports:
      - "43306:3306"
    environment:
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=pass_local_user
      - MYSQL_PASSWORD=passlocal123
      - MYSQL_ROOT_PASSWORD=passlocal123
      - TZ=Asia/Seoul